' Core Abstract Classes
abstract GameObject $basic {
  + GameObject()
  + {abstract} HandleInput()
  + {abstract} Update()
  + {abstract} Render(Graphics&)
  + ~GameObject()
}

abstract class InputComponent $base_component $input_component {
  + InputComponent()
  + {abstract} HandleInput(GameObject&)
  # IsKeyDown(KeyboardKey) : bool
  # GetMousePosition() : Position2D
  # GetMouseWheelMove() : float
  # Clamp(float, float, float) : float
  + ~InputComponent()
}

abstract class GraphicsComponent $base_component $graphics_component {
  + GraphicsComponent()
  + {abstract} Render(GameObject&, Graphics&)
  + ~GraphicsComponent()
}

abstract class UpdateComponent $base_component $update_component {
  + UpdateComponent()
  + {abstract} Update(GameObject&)
  + ~UpdateComponent()
}

class GameArea $interface {
  + Rectangle2D position
  + int priority
  + GameArea(GameObject&, Rectangle2D, int)
  + HandleInput()
  + Update()
  + Render(Graphics&)
  + ~GameArea()
  - GameObject& object
}

class GameInterface $interface {
  + GameInterface()
  + Add(GameArea&)
  + HandleInput()
  + Update()
  + Render(Graphics&)
  + ~GameInterface()
  - vector<GameArea*> gameAreas
}

class GameWorld $game_world {
  + int MapWidth
  + int MapHeight
  + {static} NewWorld(int, int, TilesManager&) : GameWorld
  + GameWorld(int, int, TilesManager&, InputComponent&, GraphicsComponent&)
  + operator[](Position2D) : WorldTile&
  + begin() : WorldTile*
  + end() : WorldTile*
  + HandleInput()
  + Update()
  + Render(Graphics&)
  + GetTilesManager() : TilesManager&
  + ~GameWorld()
  - InputComponent& input
  - GraphicsComponent& render
  - GameCamera* camera
  - bool initialized
  - vector<WorldTile> grid
  - const TilesManager& tilesManager
  - initializeGrid()
  - initializeTyleTypes()
  - afterScreenInitialization(Graphics&)
}

class GameCamera $game_world {
  + const float ZOOM_SPEED
  + const float MOVE_SPEED
  + const float ZOOM_MIN
  + const float ZOOM_MAX
  + Vector2 offset
  + Vector2 target
  + float rotation
  + float zoom
  + GameCamera(InputComponent&, GraphicsComponent&)
  + HandleInput()
  + Update()
  + Render(Graphics&)
  + UpdateFromCamera2D(Camera2D)
  + operator Camera2D() : Camera2D
  + ~GameCamera()
  - InputComponent& input
  - GraphicsComponent& graphic
}

' World Tiles
class "WorldTile \n[typed object of type TerrainType]" as WorldTile $game_world {
  + bool Dirty
  + Position2D Pos
  + WorldTileDecoration* Decoration
  + WorldTileResource* Resource
  + int MowementSpeed
  + HandleInput()
  + Update()
  + Render(Graphics&)
  + Texture() : Texture2D&
  + TextureImage() : Image&
  + ~WorldTile()
  - WorldTile(WorldTileTerrainType&, Position2D)
  - const WorldTileTerrainType& TerrainType
  - drawIsoTileFrame(Graphics&)
}

class WorldTileTerrainType $game_world {
  + WorldTileTerrainType(string, float, bool, string, Rectangle)
  + NewTile(Position2D) : WorldTile*
  + LoadTexture(Graphics&)
  + Texture() : Texture2D&
  + TextureImage() : Image&
  + ~WorldTileTerrainType()
  - string name
  - string texurePath
  - bool isWater
  - float baseMovingSpeed
  - Rectangle textureSrcRect
  - Texture2D textureObj
  - Image textureImage
  - bool initialized
  - emptyTextureSrcRect() : bool
}

' Managers
class TilesManager $game_world $resources_manager {
  + TilesManager()
  + LoadTextures(Graphics&)
  + Type(string) : WorldTileTerrainType&
  + TileTypes() : vector<string>
  + TileTypes() : unordered_map<string, WorldTileTerrainType>&
  + ~TilesManager()
  - unordered_map<string, WorldTileTerrainType> tileTypes
}

' Menus
class Menu $interface $menu {
  + Rectangle2D Position
  + HandleInput()
  + Update()
  + Render(Graphics&)
  + ~Menu()
  # Menu(GameObject&, Rectangle2D, InputComponent&, UpdateComponent&, GraphicsComponent&)
  - GameObject& binding
  - InputComponent& input
  - UpdateComponent& update
  - GraphicsComponent& graphics
}

class DecorationMenu $interface $menu {
  # DecorationMenu(GameObject&, Rectangle2D, InputComponent&, UpdateComponent&, GraphicsComponent&)
}

class MenuFactory $interface $menu {
  + {static} CreateDecorationMenu(GameWorld&, Rectangle2D) : DecorationMenu
}

together {
  ' Data Classes
  class Position2D $basic {
    + float x
    + float y
    + Position2D(Vector2)
    + Position2D(float, float)
    + Position2D(int, int)
    + operator Vector2() : Vector2
    + operator+=(Position2D&) : Position2D&
  }

  class Rectangle2D $basic {
    + float x
    + float y
    + float width
    + float height
    + Rectangle2D(Rectangle)
    + Rectangle2D(float, float, float, float)
    + ~Rectangle2D()
  }
}

class Graphics $graphics_system {
  + int ScreenWidh
  + int ScreenHeight
  + float TileWidth
  + float TileHeight
  + int TargetFrameRate
  + const char* Title
  + bool Initialized
  + Image* Dst
  + Position2D Correction
  + Camera2D camera
  + Graphics(int, int, float, float, const char*, int)
  + InitScreen()
  + BeginDrawing()
  + EndDrawing()
  + BeginMode2D(Camera2D)
  + EndMode2D()
  + Done() : bool
  + LoadTextures(const char*) : Texture2D
  + LoadImage(const char*) : Image
  + LoadImageFromTexture(Texture2D) : Image
  + LoadTextureFromImage(Image) : Texture2D
  + DrawDiamondFrame(Position2D, Color, bool, float)
  + DrawRectangle(Rectangle2D)
  + GridToScreen(Position2D) : Position2D
  + ScreenToWorld2D(Position2D) : Position2D
  + MouseToWorld2D() : Position2D
  + ~Graphics()
  - Texture2D tileOcean
  - Texture2D tileGround
  - gridToScreen(int, int) : Vector2
  - screenToGrid(Vector2) : Vector2
  - drawIsoTileFrame(int, int, Color, float)
}

Position2D -[hidden]> Graphics

' Relationships - Inheritance
GameObject <|-- GameArea
GameObject <|-- GameInterface
GameObject <|-- GameWorld
GameObject <|-- GameCamera
GameObject <|-- WorldTile
GameObject <|-- Menu
class DecorationMenu extends Menu

' Relationships - Composition
GameArea *-- GameObject : object
GameArea *-- Rectangle2D : position
GameInterface o-- GameArea : gameAreas
GameWorld *-- InputComponent : input
GameWorld *-- GraphicsComponent : render
GameWorld *-- GameCamera : camera
GameWorld o-- WorldTile : grid
GameWorld o-- TilesManager : tilesManager
GameCamera *-- InputComponent : input
GameCamera *-- GraphicsComponent : graphic
WorldTile *-- WorldTileTerrainType : TerrainType
WorldTile *-- Position2D : Pos
TilesManager o-- WorldTileTerrainType : tileTypes
Menu *-- GameObject : binding
Menu *-- InputComponent : input
Menu *-- UpdateComponent : update
Menu *-- GraphicsComponent : graphics
Menu *-- Rectangle2D : Position

' Factory Pattern
MenuFactory ..> DecorationMenu : creates
MenuFactory ..> Menu : creates

' Usage Dependencies
GameWorld ..> Graphics : uses
GameCamera ..> Graphics : uses
WorldTile ..> Graphics : uses
Graphics ..> Position2D : uses
WorldTileTerrainType ..> Graphics : uses
TilesManager ..> Graphics : uses


